name: clean_project_cli
description: Save disk space, clean any project following .gitignore.
version: 1.1.0
repository: https://github.com/sanihaq/clean_project_cli

environment:
  sdk: ^3.0.3

executables:
  cleanproject: clean_project_cli

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
